'use client';

import React, { useRef } from 'react';
import { AuditResult } from '@/lib/auditor';
import { Button } from '../../_components/ui';
import { Download, Share2, Copy, Twitter, Linkedin, Link2 } from 'lucide-react';

interface ShareDownloadProps {
    result: AuditResult;
    repoUrl: string;
    className?: string;
}

export function ShareDownload({ result, repoUrl, className = '' }: ShareDownloadProps) {
    const [copied, setCopied] = React.useState(false);
    const [showShareMenu, setShowShareMenu] = React.useState(false);

    const generateShareUrl = () => {
        const params = new URLSearchParams({
            url: repoUrl,
            spend: result.estimatedMonthlySpend.toString(),
            savings: result.optimizations.reduce((acc, o) => acc + o.projectedSavings, 0).toString(),
            providers: result.detectedStack.providers.join(',')
        });
        return `https://p402.io/dashboard/audit?${params.toString()}`;
    };

    const generateShareText = () => {
        const totalSavings = result.optimizations.reduce((acc, o) => acc + o.projectedSavings, 0);
        return `🔥 Just audited my AI costs with @p402io!\n\n💰 Current monthly spend: $${result.estimatedMonthlySpend.toLocaleString()}\n✨ Potential savings: $${totalSavings.toLocaleString()}/mo (${Math.round((totalSavings / result.estimatedMonthlySpend) * 100)}%)\n\nAudit your AI costs free: p402.io`;
    };

    const copyToClipboard = async (text: string) => {
        try {
            await navigator.clipboard.writeText(text);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    const downloadAsJSON = () => {
        const data = {
            generatedAt: new Date().toISOString(),
            repoUrl,
            ...result,
            _meta: {
                poweredBy: 'P402.io',
                version: '2.0',
                website: 'https://p402.io'
            }
        };

        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `p402-audit-${new Date().toISOString().split('T')[0]}.json`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const downloadAsMarkdown = () => {
        const totalSavings = result.optimizations.reduce((acc, o) => acc + o.projectedSavings, 0);

        const md = `# P402 AI Cost Audit Report

> Generated by [P402.io](https://p402.io) on ${new Date().toLocaleDateString()}

## Executive Summary

| Metric | Value |
|--------|-------|
| **Repository** | ${repoUrl} |
| **Monthly Spend** | $${result.estimatedMonthlySpend.toLocaleString()} |
| **Potential Savings** | $${totalSavings.toLocaleString()} |
| **Detected Providers** | ${result.detectedStack.providers.join(', ')} |
| **Analysis Confidence** | ${result.confidence}% |

## Detected AI Stack

### Providers
${result.detectedStack.providers.map(p => `- ${p}`).join('\n')}

### Models
${result.detectedStack.models.map(m => `- ${m}`).join('\n')}

### Frameworks
${result.detectedStack.frameworks.length > 0 ? result.detectedStack.frameworks.map(f => `- ${f}`).join('\n') : '- None detected'}

### Usage Patterns
${result.detectedStack.patterns.length > 0 ? result.detectedStack.patterns.map(p => `- ${p}`).join('\n') : '- Standard API usage'}

## Cost Breakdown

| Provider | Model | Monthly Cost | Calls/Day |
|----------|-------|--------------|-----------|
${result.usageBreakdown.map(u => `| ${u.provider} | ${u.model} | $${u.estimatedCost.toLocaleString()} | ${u.callsPerDay.toLocaleString()} |`).join('\n')}

## Optimization Recommendations

${result.optimizations.map((opt, i) => `### ${i + 1}. ${opt.title}

**Impact:** ${opt.impact} | **Effort:** ${opt.effort} | **Savings:** $${opt.projectedSavings}/mo

${opt.description}

\`\`\`${result.detectedStack.language}
${opt.codeExample}
\`\`\`
`).join('\n')}

## Scaling Projections

| Daily Calls | Legacy Cost | P402 Cost | Savings |
|-------------|-------------|-----------|---------|
${result.scalingAnalysis.map(s => `| ${s.callsPerDay.toLocaleString()} | $${s.legacyMonthly.toLocaleString()} | $${s.p402Monthly.toLocaleString()} | ${s.savingsPercent}% |`).join('\n')}

## Quick Start Integration

\`\`\`bash
${result.deploymentGuide.sdkInstall}
\`\`\`

\`\`\`${result.detectedStack.language}
${result.deploymentGuide.quickStart}
\`\`\`

---

**Powered by [P402.io](https://p402.io)** - The AI Cost Optimization Platform

🚀 Start saving today: [https://p402.io/get-access](https://p402.io/get-access)
`;

        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `p402-audit-${new Date().toISOString().split('T')[0]}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const shareToTwitter = () => {
        const text = encodeURIComponent(generateShareText());
        window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
    };

    const shareToLinkedIn = () => {
        const url = encodeURIComponent(generateShareUrl());
        const title = encodeURIComponent('AI Cost Audit by P402.io');
        const summary = encodeURIComponent(`Discovered $${result.optimizations.reduce((acc, o) => acc + o.projectedSavings, 0).toLocaleString()}/mo in potential AI savings!`);
        window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}`, '_blank');
    };

    return (
        <div className={`relative ${className}`}>
            <div className="flex gap-3">
                {/* Download Button */}
                <div className="relative group">
                    <Button
                        variant="secondary"
                        size="sm"
                        className="gap-2"
                        onClick={downloadAsMarkdown}
                    >
                        <Download size={16} />
                        <span className="hidden sm:inline">Download Report</span>
                    </Button>

                    {/* Dropdown */}
                    <div className="absolute top-full left-0 mt-2 w-48 bg-white border-4 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-50">
                        <button
                            onClick={downloadAsMarkdown}
                            className="w-full px-4 py-3 text-left text-xs font-bold uppercase hover:bg-neutral-50 border-b border-black/10"
                        >
                            📄 Markdown (.md)
                        </button>
                        <button
                            onClick={downloadAsJSON}
                            className="w-full px-4 py-3 text-left text-xs font-bold uppercase hover:bg-neutral-50"
                        >
                            📊 Data (.json)
                        </button>
                    </div>
                </div>

                {/* Share Button */}
                <div className="relative">
                    <Button
                        variant="dark"
                        size="sm"
                        className="gap-2"
                        onClick={() => setShowShareMenu(!showShareMenu)}
                    >
                        <Share2 size={16} />
                        <span className="hidden sm:inline">Share Results</span>
                    </Button>

                    {/* Share Menu */}
                    {showShareMenu && (
                        <>
                            <div
                                className="fixed inset-0 z-40"
                                onClick={() => setShowShareMenu(false)}
                            />
                            <div className="absolute top-full right-0 mt-2 w-64 bg-black text-white border-4 border-primary shadow-[8px_8px_0px_0px_rgba(182,255,46,0.5)] z-50 animate-in fade-in zoom-in-95 duration-200">
                                <div className="p-4 border-b border-neutral-800">
                                    <div className="text-[10px] font-bold uppercase text-neutral-500 mb-2">Share To</div>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={shareToTwitter}
                                            className="flex-1 p-3 bg-neutral-900 hover:bg-neutral-800 transition-colors flex items-center justify-center gap-2 text-xs font-bold"
                                        >
                                            <Twitter size={16} />
                                            Twitter
                                        </button>
                                        <button
                                            onClick={shareToLinkedIn}
                                            className="flex-1 p-3 bg-neutral-900 hover:bg-neutral-800 transition-colors flex items-center justify-center gap-2 text-xs font-bold"
                                        >
                                            <Linkedin size={16} />
                                            LinkedIn
                                        </button>
                                    </div>
                                </div>

                                <div className="p-4">
                                    <div className="text-[10px] font-bold uppercase text-neutral-500 mb-2">Copy Link</div>
                                    <div className="flex gap-2">
                                        <input
                                            type="text"
                                            value={generateShareUrl()}
                                            readOnly
                                            className="flex-1 bg-neutral-900 text-[10px] font-mono p-2 border border-neutral-700 text-neutral-300"
                                        />
                                        <button
                                            onClick={() => copyToClipboard(generateShareUrl())}
                                            className="p-2 bg-primary text-black hover:bg-primary/90 transition-colors"
                                        >
                                            {copied ? '✓' : <Copy size={16} />}
                                        </button>
                                    </div>
                                </div>

                                <div className="p-4 border-t border-neutral-800">
                                    <button
                                        onClick={() => copyToClipboard(generateShareText())}
                                        className="w-full p-3 bg-primary text-black font-bold text-xs uppercase hover:bg-primary/90 transition-colors flex items-center justify-center gap-2"
                                    >
                                        <Copy size={14} />
                                        Copy Share Text
                                    </button>
                                </div>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
}

// ============================================================================
// SOCIAL CARD PREVIEW
// ============================================================================

interface SocialCardProps {
    result: AuditResult;
    repoUrl: string;
}

export function SocialCard({ result, repoUrl }: SocialCardProps) {
    const totalSavings = result.optimizations.reduce((acc, o) => acc + o.projectedSavings, 0);
    const savingsPercent = Math.round((totalSavings / result.estimatedMonthlySpend) * 100);

    return (
        <div className="w-full max-w-lg mx-auto bg-black text-white p-8 border-4 border-primary relative overflow-hidden">
            {/* Background Pattern */}
            <div className="absolute inset-0 opacity-5">
                <div className="absolute inset-0" style={{
                    backgroundImage: 'repeating-linear-gradient(45deg, #B6FF2E 0, #B6FF2E 1px, transparent 0, transparent 50%)',
                    backgroundSize: '20px 20px'
                }} />
            </div>

            {/* Content */}
            <div className="relative z-10 space-y-6">
                {/* Header */}
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <img src="/favicon.png" alt="P402" className="w-8 h-8 border-2 border-primary" />
                        <span className="font-black uppercase italic text-xl">P402<span className="text-primary">.io</span></span>
                    </div>
                    <span className="text-[10px] font-bold uppercase text-neutral-500">AI Cost Audit</span>
                </div>

                {/* Main Stats */}
                <div className="space-y-4">
                    <div className="text-center">
                        <div className="text-[10px] font-bold uppercase text-neutral-500 mb-1">Current Monthly Spend</div>
                        <div className="text-5xl font-black font-mono text-primary">
                            ${result.estimatedMonthlySpend.toLocaleString()}
                        </div>
                    </div>

                    <div className="flex justify-center gap-8 py-4 border-y border-neutral-800">
                        <div className="text-center">
                            <div className="text-3xl font-black text-white">{result.detectedStack.providers.length}</div>
                            <div className="text-[10px] font-bold uppercase text-neutral-500">Providers</div>
                        </div>
                        <div className="text-center">
                            <div className="text-3xl font-black text-primary">-{savingsPercent}%</div>
                            <div className="text-[10px] font-bold uppercase text-neutral-500">Savable</div>
                        </div>
                        <div className="text-center">
                            <div className="text-3xl font-black text-white">${totalSavings.toLocaleString()}</div>
                            <div className="text-[10px] font-bold uppercase text-neutral-500">Savings</div>
                        </div>
                    </div>
                </div>

                {/* CTA */}
                <div className="text-center">
                    <div className="text-sm font-bold text-neutral-400">Audit your AI costs free at</div>
                    <div className="text-xl font-black text-primary">p402.io</div>
                </div>
            </div>
        </div>
    );
}
