/**
 * Prebuild hook: snapshot OpenRouter's live model catalog into a generated
 * TS module that the OpenRouter adapter imports as its cold-start state.
 *
 * Why this exists
 * ---------------
 * The adapter ships with a hand-curated static fallback. That fallback is
 * the cold-start catalog: on a brand-new serverless instance, the very
 * first request lands before the runtime `refreshLiveCatalog()` background
 * fetch completes. If the static list carries a speculative id that
 * OpenRouter has retired, that first request 400s with "is not a valid
 * model ID" (this is exactly the gemini-3-flash / gpt-5.2 incident from
 * commits 253cb58 and badf010).
 *
 * Snapshotting the live catalog at build time fixes the class of bug:
 * each deploy starts from whatever OpenRouter currently serves. The
 * runtime refresh stays in place for sub-deploy freshness; this script
 * just removes the cold-start window where the static list is the only
 * source of truth.
 *
 * Failure posture
 * ---------------
 * Network blip during `vercel build`? The script logs and exits 0,
 * leaving the previously committed snapshot intact. Builds never fail
 * because of this — the adapter's hand-curated static fallback is always
 * the last line of defense.
 *
 * Run manually:  npx tsx scripts/build-openrouter-catalog.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadLiveCatalog } from '../lib/ai-providers/openrouter-live-catalog.js';
import type { ModelInfo } from '../lib/ai-providers/types.js';

const OUT_PATH = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '..',
    'lib',
    'ai-providers',
    'openrouter-catalog.generated.ts',
);

function serialize(models: ModelInfo[]): string {
    const header = `/* eslint-disable */
// AUTO-GENERATED by scripts/build-openrouter-catalog.ts.
// Regenerated on every prebuild via the live OpenRouter /api/v1/models
// endpoint. Do not edit by hand; edits are clobbered on the next build.
// The hand-curated static fallback lives in openrouter.ts.

import type { ModelInfo } from './types';

export const GENERATED_AT = ${Date.now()};
export const GENERATED_OPENROUTER_CATALOG: ModelInfo[] = ${JSON.stringify(models, null, 2)};
`;
    return header;
}

function emitEmpty(reason: string): void {
    const stub = `/* eslint-disable */
// AUTO-GENERATED placeholder. Live OpenRouter fetch unavailable at build
// time (${reason}); the adapter will fall back to its hand-curated static
// catalog. Next successful build will overwrite this file.

import type { ModelInfo } from './types';

export const GENERATED_AT = 0;
export const GENERATED_OPENROUTER_CATALOG: ModelInfo[] = [];
`;
    writeFileSync(OUT_PATH, stub, 'utf8');
}

async function main(): Promise<void> {
    const skip = process.env.SKIP_OPENROUTER_CATALOG_BUILD === '1';
    if (skip) {
        console.log('[build-openrouter-catalog] SKIP_OPENROUTER_CATALOG_BUILD=1, skipping');
        return;
    }

    try {
        const models = await loadLiveCatalog({
            apiKey:  process.env.OPENROUTER_API_KEY,
            referer: process.env.OPENROUTER_REFERER || 'https://p402.io',
        });
        if (models.length === 0) {
            console.warn('[build-openrouter-catalog] live catalog returned 0 mappable rows; emitting empty stub');
            emitEmpty('zero mappable rows');
            return;
        }
        writeFileSync(OUT_PATH, serialize(models), 'utf8');
        console.log(`[build-openrouter-catalog] wrote ${models.length} models to ${OUT_PATH}`);
    } catch (err) {
        const msg = (err as Error)?.message ?? String(err);
        console.warn(`[build-openrouter-catalog] fetch failed, leaving existing snapshot intact: ${msg}`);
    }
}

main().catch((err) => {
    console.warn('[build-openrouter-catalog] unexpected error, exiting 0:', err);
});
