export interface OptimizeThresholds {
  OUTCOME_COVERAGE_MIN: number;
  ACCEPTED_OUTCOME_MIN: number;
  BASELINE_WINDOW_DAYS: number;
  ATTRIBUTION_GAP_MAX: number;
  CONFIDENCE_MIN: number;
  SLICE_TRAFFIC_MIN: number;
  POSTPERIOD_WINDOW_DAYS: number;
  OUTCOME_DEGRADATION_MAX: number;
}

export const DEFAULT_THRESHOLDS: OptimizeThresholds = {
  OUTCOME_COVERAGE_MIN: 0.6,
  ACCEPTED_OUTCOME_MIN: 50,
  BASELINE_WINDOW_DAYS: 14,
  ATTRIBUTION_GAP_MAX: 0.1,
  CONFIDENCE_MIN: 0.7,
  SLICE_TRAFFIC_MIN: 0.02,
  POSTPERIOD_WINDOW_DAYS: 14,
  OUTCOME_DEGRADATION_MAX: 0.05,
};

function num(name: string, fallback: number): number {
  const raw = process.env[name];
  if (raw === undefined || raw === '') return fallback;
  const parsed = Number(raw);
  if (!Number.isFinite(parsed)) return fallback;
  return parsed;
}

export function loadThresholds(): OptimizeThresholds {
  return {
    OUTCOME_COVERAGE_MIN: num('OPTIMIZE_OUTCOME_COVERAGE_MIN', DEFAULT_THRESHOLDS.OUTCOME_COVERAGE_MIN),
    ACCEPTED_OUTCOME_MIN: num('OPTIMIZE_ACCEPTED_OUTCOME_MIN', DEFAULT_THRESHOLDS.ACCEPTED_OUTCOME_MIN),
    BASELINE_WINDOW_DAYS: num('OPTIMIZE_BASELINE_WINDOW_DAYS', DEFAULT_THRESHOLDS.BASELINE_WINDOW_DAYS),
    ATTRIBUTION_GAP_MAX: num('OPTIMIZE_ATTRIBUTION_GAP_MAX', DEFAULT_THRESHOLDS.ATTRIBUTION_GAP_MAX),
    CONFIDENCE_MIN: num('OPTIMIZE_CONFIDENCE_MIN', DEFAULT_THRESHOLDS.CONFIDENCE_MIN),
    SLICE_TRAFFIC_MIN: num('OPTIMIZE_SLICE_TRAFFIC_MIN', DEFAULT_THRESHOLDS.SLICE_TRAFFIC_MIN),
    POSTPERIOD_WINDOW_DAYS: num('OPTIMIZE_POSTPERIOD_WINDOW_DAYS', DEFAULT_THRESHOLDS.POSTPERIOD_WINDOW_DAYS),
    OUTCOME_DEGRADATION_MAX: num('OPTIMIZE_OUTCOME_DEGRADATION_MAX', DEFAULT_THRESHOLDS.OUTCOME_DEGRADATION_MAX),
  };
}
